### ISSUE TITLE
Request: archive and dead

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/ftheadshots#119]
Since FT Author headshots are now handled somewhere other than https://github.com/Financial-Times/headshot-images -- should we dead & archive this project?

**Comment by notlee** [comment]
As in Slack:
>Do existing headshots before the change still come from our imageset? I don’t think we can dead until the image set isn’t used.

**Comment by JakeChampion** [comment]
Yes they do but we are not supporting them at all, which is how we define a "dead" component. I think we can dead it because the previously published versions will still exist

**Comment by notlee** [comment]
That seems fair, my only hesitation is a future Origami person might assume a bucket for a dead imageset can be safety deleted.
