### ISSUE TITLE
Add section to readme explaining new process before archiving?

### ISSUE THREAD

**Issue by chee** [Financial-Times/ftheadshots#121]
Maybe (based on this comment from @notlee https://github.com/Financial-Times/ftheadshots/issues/119#issuecomment-581499597) we should add a section to the README.md explaining the new process and not to delete the bucket, before archiving the repo?

_Originally posted by @chee in https://github.com/Financial-Times/ftheadshots/pull/120#issuecomment-582321392_

**Comment by JakeChampion** [comment]
I think that already is there.

> Information on the new process is available here: https://github.com/Financial-Times/origami/issues/16
>https://github.com/Financial-Times/ftheadshots/blob/master/README.md

**Comment by chee** [comment]
ph yeah i did that:) never closed this
